INSERT INTO tbl_cards (name, hp, type, stage, info, attack, damage, weak, resist, retreat, collection_id) VALUES 
('Pikachu', 60, 'Electric', 'Basic', 'A mouse Pokémon with electric abilities.', 'Thunder Shock', '20', 'Fighting', '', 1, 1),
('Charizard', 120, 'Fire', 'Stage 2', 'A powerful Fire-type Pokémon.', 'Fire Spin', '100', 'Water', '', 3, 1),
('Blastoise', 100, 'Water', 'Stage 2', 'A Water-type Pokémon with strong defense.', 'Hydro Pump', '60+', 'Electric', '', 3, 1),
('Venusaur', 100, 'Grass', 'Stage 2', 'A Grass-type Pokémon with healing abilities.', 'Solarbeam', '80', 'Fire', '', 2, 1),
('Gengar', 80, 'Psychic', 'Stage 2', 'A ghost Pokémon known for tricks.', 'Shadow Ball', '50', 'Dark', '', 1, 2),
('Machamp', 100, 'Fighting', 'Stage 2', 'A four-armed Pokémon with immense strength.', 'Dynamic Punch', '80', 'Psychic', '', 2, 2),
('Alakazam', 80, 'Psychic', 'Stage 2', 'A highly intelligent Pokémon with telepathic powers.', 'Mind Blast', '60+', 'Dark', '', 1, 2),
('Jolteon', 90, 'Electric', 'Stage 1', 'A fast Pokémon with strong electric attacks.', 'Thunderbolt', '90', 'Ground', '', 1, 3),
('Vaporeon', 110, 'Water', 'Stage 1', 'A water Pokémon with agile movements.', 'Aqua Tail', '70+', 'Electric', '', 2, 3),
('Flareon', 100, 'Fire', 'Stage 1', 'A fire Pokémon with intense flames.', 'Flame Thrower', '80', 'Water', '', 2, 3),
('Snorlax', 130, 'Normal', 'Basic', 'A large Pokémon known for sleeping.', 'Body Slam', '50', 'Fighting', '', 4, 4),
('Dragonite', 120, 'Dragon', 'Stage 2', 'A powerful dragon Pokémon.', 'Hyper Beam', '100+', 'Fairy', '', 3, 4),
('Gyarados', 130, 'Water', 'Stage 1', 'A fearsome water Pokémon.', 'Hydro Blast', '90+', 'Electric', '', 3, 5),
('Magneton', 90, 'Electric', 'Stage 1', 'A magnet Pokémon with strong electrical forces.', 'Electromagnetic Pulse', '70', 'Ground', '', 2, 5),
('Scizor', 100, 'Metal', 'Stage 1', 'A steel Pokémon with sharp claws.', 'Steel Wing', '80', 'Fire', '', 2, 6),
('Heracross', 90, 'Fighting', 'Basic', 'A bug Pokémon with strong physical strength.', 'Megahorn', '100', 'Psychic', '', 3, 6),
('Togekiss', 120, 'Fairy', 'Stage 2', 'A Pokémon known for kindness and joy.', 'Fairy Wind', '80', 'Steel', '', 1, 7),
('Espeon', 110, 'Psychic', 'Stage 1', 'A Pokémon with deep mental powers.', 'Psybeam', '70+', 'Dark', '', 2, 7),
('Umbreon', 110, 'Dark', 'Stage 1', 'A mysterious Pokémon with shadow abilities.', 'Night Slash', '90', 'Fighting', '', 2, 7),
('Lucario', 110, 'Fighting', 'Stage 1', 'A Pokémon with incredible aura sensing abilities.', 'Aura Sphere', '80+', 'Psychic', '', 3, 8);
